[tool.poetry]
name = "nutriweb"
version = "0.1.0"
description = "A personalized product recommendation system."
authors = ["Thanvitha <m.thanvitha@gmail.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.9.8,<4.0"
pandas = "^1.5.3"
numpy = "^1.23.5"
flask = "^3.1.0"
streamlit = "^1.43.2"
sentence-transformers = "^4.0.2"
faiss-cpu = "^1.10.0"
gdown = "^5.2.0"
plotly = "^6.0.1"
huggingface-hub = "^0.30.2"
pymongo = "^4.12.1"
certifi = "^2025.4.26"


[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

# Use double square brackets for an array of tables.
[[tool.poetry.packages]]
include = "nutriweb"
from = "."

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
