# Risk levels for various ingredients/additives.
# All keys should be in lowercase.
RISK_LEVELS = {
    "water" : "Safe",
    "high fructose corn syrup": "Avoid",
    "wheat gluten": "Caution",
    "butter": "Caution",
    "carbonated water": "Safe",
    "sugar": "Caution",
    "glucose": "Caution",
    "citric acid": "Safe",
    "natural flavors": "Safe",
    "artificial flavors": "Caution",
    "taurine": "Safe",
    "sodium citrate": "Safe",
    "color added": "Caution",
    "panax ginseng extract": "Caution",
    "L-Carnitine L-Tartrate": "Safe",
    "caffeine": "Caution",
    "sorbic acid": "Safe",
    "benzoic acid": "Caution",
    "niacinamide": "Safe",
    "sucralose": "Avoid",
    "salt": "Safe",
    "eau gazéifiée": "Safe",
    "sucre": "Caution",
    "colorant caramel e150d":"Caution" ,
    "acidifiant": "Caution",
    "arômes": "Safe",
    "brewed starbucks coffee": "Safe",
    "reduced-fat _milk_": "Safe",
    "pectin.": "Safe",
    "potassium bromate": "Avoid",
    "propylparaben": "Avoid",
    "bha": "Avoid",
    "bht": "Avoid",
    "sodium benzoate": "Avoid",
    "titanium dioxide": "Avoid",
    "sodium nitrite": "Avoid",
    "red 3": "Avoid",
    "red 40": "Avoid",
    "red 40 lake": "Avoid",
    "yellow 5": "Avoid",
    "yellow 5 lake": "Avoid",
    "yellow 6": "Avoid",
    "blue 1": "Avoid",
    "blue 2": "Avoid",
    "green 3": "Avoid",
    "aspartame": "Avoid",
    "ada": "Avoid",
    "propylgallate": "Avoid",
    "methylene chloride": "Avoid",
    "trichloroethylene": "Avoid",
    "ethylene dichloride": "Avoid",
    "pfas": "Avoid",
    "phthalates": "Avoid",
    "brominated vegetable oil": "Avoid",
    "sodium nitrate": "Avoid",
    "acesulfame potassium": "Avoid",
    "advantame": "Avoid",
    "neotame": "Avoid",
    "saccharin": "Avoid",


    #risk levels of additives

    "e101": "Safe",
    "e101i": "Safe",
    "e282": "Caution",
    "sodium nitrite": "Avoid",  # ensure sodium nitrite is marked as high risk
    "e1103": "Safe",
    "e420i": "Caution",
    "e955": "Caution",
    "e210": "Avoid",
    "e513": "Avoid",
    "e450": "Caution",
    "e100": "Safe",
    "e318": "Safe",
    "e281": "Caution",
    "e327": "Safe",
    "e555": "Avoid",
    "e200": "Safe",
    "e330": "Safe",
    "e331": "Safe",
    "e150d": "Safe",
    "e338": "Caution",
    "e440": "Safe",
    "e440i": "Safe",
}
