#  .streamlit/secrets.toml

# Your connection string—replace USER, PASS, HOST, etc. as needed
MONGODB_URI = "mongodb+srv://nutriweb_user:nutriweb1@nutriweb.6abotjz.mongodb.net/?retryWrites=true&w=majority&appName=Nutriweb"

# (Optional) default database name
MONGO_DB_NAME = "nutriweb_db"